export const REQUEST_BUSINESS_LOG_DATA = "REQUEST_BUSINESS_LOG_DATA";
export const RECEIVE_BUSINESS_LOG_DATA = "RECEIVE_BUSINESS_LOG_DATA";
export const SEARCH_BUSINESS_LOG_DATA = "SEARCH_BUSINESS_LOG_DATA";
