export const REQUEST_BUSINESS_LOG_DATA = "REQUEST_BUSINESS_LOG_DATA";
export const RECEIVE_BUSINESS_LOG_DATA = "RECEIVE_BUSINESS_LOG_DATA";
export const SEARCH_BUSINESS_LOG_DATA = "SEARCH_BUSINESS_LOG_DATA";
export const REQUEST_CREATE_BUSINESS = "REQUEST_CREATE_BUSINESS";
export const DELETE_BUSINESS_DATA = "DELETE_BUSINESS_DATA";
